FROM python:3.11

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

WORKDIR /app/tasks

RUN chmod +x entrypoint.sh

ENTRYPOINT ["sh", "/app/tasks/entrypoint_worker.sh"]
